### PR TITLE
revive header logo to return home

### PR DESCRIPTION
**Pull request by hypha**
It wasn't easy to go back to home page otherwise :)

### CODE REVIEW

**Comment by patrick91** [comment]
Nice! do you think we should change the logo to have better contrast with the bg? 

CleanShot 2024-03-08 at 12 53 33@2x

**Comment by hypha** [comment]
> Nice! do you think we should change the logo to have better contrast with the bg?
> 
> CleanShot 2024-03-08 at 12 53 33@2x

I was thinking the same thing and thought the pink & blue one might be better for contrast against white. 
image

**Review by thepetk — APPROVED** [review]
lgtm

**Comment by hypha** [comment]
@patrick91 @thepetk @artcz perhaps the current blue and pink looks better for contrast ( https://github.com/EuroPython/website/pull/489/commits/eac16dc80becf28620dd97891f15f31e25c1ad4b) like this?
image
 

I think this one is part of the hero and not componentised separately as a logo, which might not be easy to use in comparison? 
image

If you are happy for the current version, feel free to merge or discuss which colours you'd like or take over entirely ofc :)

**Comment by hypha** [comment]
hey hey! any thoughts on whether the current version can be merged or it should be modified in any specific direction? :hugs:

**Pull request merged**
