### PR TITLE
1pass logo

### PR DESCRIPTION
**Pull request by Ladybiss**

### CODE REVIEW

**Comment by artcz** [comment]
image
I think something went wrong here :sweat_smile:

**Comment by Ladybiss** [comment]
> image I think something went wrong here 😅

yep 😁 That's one of the reasons I didn't merge yet!

**Comment by hypha** [comment]
> > image I think something went wrong here sweat_smile
> 
> yep grin That's one of the reasons I didn't merge yet!

should look good now?

**Comment by patrick91** [comment]
@hypha @Ladybiss I've done some changes to the css 😊 they might break when we get more lines of sponsors but I'll happily fix it then :)

**Comment by hypha** [comment]
> @hypha @Ladybiss I've done some changes to the css 😊 they might break when we get more lines of sponsors but I'll happily fix it then :)

Your promise is better than anything we can hope for @patrick91 :)

**Pull request merged**
