### PR TITLE
Update ticket release date from 25th to 28th.

### PR DESCRIPTION
**Pull request by Vaibhavs10**

### CODE REVIEW

**Review by patrick91 — APPROVED** [review]

**Comment by hypha** [comment]
https://github.com/EuroPython/website/blob/76891a413cbb7256cfe123e4e661c1aee0e5d84d/src/content/pages/faq.mdx?plain=1#L23
I think this will need to change too.

**Comment by hypha** [comment]
I'm so sorry @Vaibhavs10! I think this needs to change too: https://github.com/EuroPython/website/blob/76891a413cbb7256cfe123e4e661c1aee0e5d84d/src/content/pages/faq.mdx?plain=1#L80
Otherwise LGTM. Sorry again!

**Review by thepetk — CHANGES_REQUESTED** [review]
Nice! Quick comment about https://github.com/EuroPython/website/blob/main/src/content/pages/faq.mdx?plain=1#L80 we also need to update this line to 28th of march!

**Comment by thepetk** [comment]
> I'm so sorry @Vaibhavs10! I think this needs to change too:
> 
> https://github.com/EuroPython/website/blob/76891a413cbb7256cfe123e4e661c1aee0e5d84d/src/content/pages/faq.mdx?plain=1#L80
> 
> 
> Otherwise LGTM. Sorry again!

Oh @hypha you were fast!

**Review by hypha — APPROVED** [review]
<3

**Review by thepetk — APPROVED** [review]
/lgtm

**Pull request merged**
