### PR TITLE
add bloombers and picnic sponsor logos

### PR DESCRIPTION
**Pull request by aramboi**

### CODE REVIEW

**Comment by hypha** [comment]
lurker passing around: there seems to be a wee grey background layer on the Bloomberg svg?

**Comment by aramboi** [comment]
> lurker passing around: there seems to be a wee grey background layer on the Bloomberg svg?

Yes indeed. I tried a few things, but in the end I've no idea how to fix that.

I've asked for help on the Discord channel in the meantime, but if you have any ideas let me know, or better yet push a commit. ☺️

**Comment by hypha** [comment]
Patrick beat me to it. You basically have to modify the svg by removing the grey layer or just extract the logo part.

**Comment by aramboi** [comment]
Thanks folks

**Pull request merged**
