### PR TITLE
Update mentorship page

### PR DESCRIPTION
**Pull request by thepetk**
## What does this PR do?:

This PR updates the existing `mentorship.md` page with 2024 information.

## Which issue(s) this PR fixes:

N/A

### CODE REVIEW

**Comment by thepetk** [comment]
For vercel `ep2024` I'd say we could force the same rule like `ep2023` to require authorization before deploy.

cc @Kislovskiy @patrick91

**Comment by Kislovskiy** [comment]
> For vercel `ep2024` I'd say we could force the same rule like `ep2023` to require authorization before deploy. wdyt?
> 
> cc @Kislovskiy @patrick91

Indeed, Pull Request from forks should not be build without approval, thanks for discovering this!

**Comment by Kislovskiy** [comment]
I've checked that we have `Git Fork Protection` enabled for each of the deployment.

**Review by Kislovskiy — APPROVED** [review]
Let's merge this, and we can adjust colors tomorrow.

**Comment by thepetk** [comment]
> Let's merge this, and we can adjust colors tomorrow.

@Kislovskiy as `ep2023` has failed I cannot merge this PR. Might need someone with the correct permissions to merge it.

**Pull request merged**
