### PR TITLE
Update humble-data.md

### PR DESCRIPTION
**Pull request by Cheukting**
A wee update on the date

### CODE REVIEW

**Comment by Cheukting** [comment]
@hypha do you know why the chromatic deployment failed? It seems not be able to initialise at some step

**Comment by hypha** [comment]
@Cheukting yup, I think it might be to do with the next's update yesterday. @patrick91 will be able to help.

**Comment by patrick91** [comment]
@Cheukting @hypha feel free to ignore that for now, it's a bug in storybook: https://github.com/storybookjs/storybook/issues/23287

**Comment by hypha** [comment]
Thanks @patrick91! @Cheukting then we can merge!

**Pull request merged**
