### PR TITLE
add 2023 keynoters

### PR DESCRIPTION
**Pull request by hypha**
- [x] add keynoters to homepage
- [x] correct layout for each keynote page 
- [x] /keynoters list the same as homepage
- [x] determine whether to pull keynote content from pretalx or manually add them
- [x] generate correct social cards
- [x] tagline styling works well even when not all have provided one.

### CODE REVIEW

**Comment by Vaibhavs10** [comment]
@patrick91/ @hypha On Johanna's image Vercel says https://ep2023-g3wpa19wl-europython-society.vercel.app says `Not passing silently`

**Comment by hypha** [comment]
> @patrick91/ @hypha On Johanna's image Vercel says https://ep2023-g3wpa19wl-europython-society.vercel.app says `Not passing silently`

That's her tagline. The others have not provided one yet.

**Comment by Vaibhavs10** [comment]
@hypha - Hmm.. can we remove that for now, and update it only when have everyones tagline?

**Comment by hypha** [comment]
@Vaibhavs10 not yet - Patrick will think a bit about how it would look like and might make some changes. I might do the same too if I find time. It won't get merged looking like that, but give some time to explore.

**Comment by hypha** [comment]
@Vaibhavs10 grey boxes fixed and the pictures were cropped to look a bit better. I've removed the tagline for now. Happy to merge?

**Review by Vaibhavs10 — APPROVED** [review]
LGTM. I'm not a huge fan of having taglines only for a few of them, but if you feel strongly about this then feel free to ship.

Good for me to merge either way!

**Pull request merged**
