### PR TITLE
Add job board from sponsor submissions

### PR DESCRIPTION
**Pull request by hypha**
FYI, I would have preferred to name the file "job board", instead of "jobs board". But that would have resulted in the sponsor info page link 404. 

Currently in draft, waiting for more submissions. Once ready, @aramboi and @laisbsc can review.

### CODE REVIEW

**Comment by aramboi** [comment]
That page is already 404 so we could just change it to link to `/job-board` to begin with. ☺️

**Comment by aramboi** [comment]
Awesome 🤩 LGTM :shipit:

**Comment by laisbsc** [comment]
Looks awesome! @aramboi sent a reminder to all sponsors for the Job Board and Virtual Swag page and no one really replied. So might be better to just merge this and add more as we get it. If we get it.

Also, something it always intrigued me was why the Job Board and Virtual Swag are not under the Sponsor menu on the website 🤔 I can never find it under Info & Support.

**Comment by hypha** [comment]
`Also something it always intrigued me was why the Job Board and Virtual Swag are not under the Sponsor menu on the website 🤔 I can never find it under Info & Support`.
Because attendees in the past said they can never find it under sponsorship 😅

**Comment by laisbsc** [comment]
> `Also something it always intrigued me was why the Job Board and Virtual Swag are not under the Sponsor menu on the website 🤔 I can never find it under Info & Support`. Because attendees in the past said they can never find it under sponsorship 😅

I'm laughing out loud! 🤣  #howtomakeusershappy?

**Comment by aramboi** [comment]
Maybe we should put the links in both submenus. I mean, I don't think it's unheard of, is it?
But for now, I'll merge like this and maybe add later. 😅

**Pull request merged**
