### PR TITLE
Change public transport phone app to Lítačka

### PR DESCRIPTION
**Pull request by jvacek**
Proposing changing this as Lítačka is not exactly that well-known by foreigners, and makes it way easier to purchase tickets.

### CODE REVIEW

**Review by Vaibhavs10 — APPROVED** [review]
Thanks for the PR. Can confirm this works! Used this last year as well!

**Comment by jvacek** [comment]
My pleasure. Any action required on my end?

**Comment by Vaibhavs10** [comment]
Thanks @patrick91 for merging! sorry @jvacek it took as awhile to get this sorted.

**Comment by jvacek** [comment]
No worries, there's plenty time ;)

**Pull request merged**
