### PR TITLE
Schedule

### PR DESCRIPTION
**Pull request by patrick91**
TODO

- [x] Fix styles
- [x] Add breaks
- [x] Add day end
- [x] Mobile design
- [x] Hide placeholders
- [x] Support for multi slot events
- [x] redirect sprint days to the /sprints page
- [x] some visual distinction between CFP tutorials (Club A,E,H,B) and Special events with registration required (Club C, D). Put the wording "separate registration required at its event page"
- [x] posters align!

(some points raised here: https://github.com/EuroPython/website/issues/306)

### CODE REVIEW

**Comment by hypha** [comment]
@patrick91 you can fetch breaks from here: 
https://pretalx.com/api/events/europython-2023/schedules/latest/?format=json

**Review by Vaibhavs10 — COMMENTED** [review]
Yo! thanks for working on this <3 
Just went through the schedule to look at possible discrepancies:
1. On tutorial days the slots look really long on the desktop, given there is uniformity in the time blocks, I say we shorten it by a factor 3 or 4? This will help everyone see the schedule on one screen.
2. All the talk URLs (atleast the ones I tried on (https://ep2023-git-feature-schedule-2023-europython-society.vercel.app/schedule/2023-07-17) failed.
3. The lunch breaks and coffee breaks are missing.
4. Is it possible to change the order of the rooms to A, B, C, D, E, and H (We can change this from the schedule as well) cc: @artcz
5. Can we reduce the difference between the height of 30 & 45-minute slots? It currently looks a bit wonky. It looks a little weird especially if there is only a single 45-minute talk in the row (10:45 on Wednesday: https://ep2023-git-feature-schedule-2023-europython-society.vercel.app/schedule/2023-07-19)
6. There's nothing on the sprints page, but you prolly know that already.

Happy to answer more questions or clarify if you want :)

**Comment by patrick91** [comment]
@Vaibhavs10 @hypha sprints days are not shown currently, since I switched to the new API, should I still add them in the list?

**Comment by patrick91** [comment]
I've changed the duration of multi slot event, to the total one, but @artcz was rightly suggesting to show the block duration on the schedule and the correct duration on the event page, I'll do that tomorrow

**Comment by hypha** [comment]
> @Vaibhavs10 @hypha sprints days are not shown currently, since I switched to the new API, should I still add them in the list?

Yes definitely. I am not sure if we will list sprints on pretalx. But it will be very helpful to list in the drop-down of the schedule and redirect to /sprints. We can add a note at the top of the /sprints page that rooms and schedule will be published closer to the sprint dates?

**Review by artcz — APPROVED** [review]

**Pull request merged**
