### PR TITLE
Add Django Girls Workshop

### PR DESCRIPTION
**Pull request by clytaemnestra**

### CODE REVIEW

**Comment by hypha** [comment]
I think some of the dates are off by one. It probably should be: 

🎤 Wed 10th - Fri 12th July: Conference talks 

💻 Sat 13th - Sun 14th July: Sprints

🤗

**Comment by hypha** [comment]
A wee thought: I wonder if it might be a good idea to mention that Django Girls was established during EuroPython 2014 Berlin, adding a celebratory note to its joyous 10th anniversary.

**Comment by clytaemnestra** [comment]
Thanks for the review.

> A wee thought: I wonder if it might be a good idea to mention that Django Girls was established during EuroPython 2014 Berlin, adding a celebratory note to its joyous 10th anniversary.

That's a great idea! I'll think how to phrase it and let you know once it's updated. 🙂

**Comment by hypha** [comment]
> Hey @hypha, I've added a note about this edition being a 10th celebration. What do you think? 🙂 https://djangogirls.org/en/prague/

Hey @clytaemnestra, I love it!

**Comment by hypha** [comment]
I seem to still have the permission to merge it, but probably good to get @cmaureir or @artcz's approval first.  :hugs:

**Comment by hypha** [comment]
merged this after Cristián's approval since I think Mia doesn't seem to have permission (yet).

**Pull request merged**
